/* Simulation code for BuildingCase3 generated by the OpenModelica Compiler OpenModelica v1.25.0 (64-bit). */
#if !defined(BuildingCase3__MODEL_H)
#define BuildingCase3__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "BuildingCase3_functions.h"

#define Modelica_Math_Vectors_length_index 0
#define Modelica_Math_Vectors_normalize_index 1
#define Modelica_Mechanics_MultiBody_Frames_Orientation_index 2
#define Modelica_Mechanics_MultiBody_Frames_resolve2_index 3
#define Modelica_Mechanics_MultiBody_Frames_TransformationMatrices_from__nxy_index 4

extern void BuildingCase3_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void BuildingCase3_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void BuildingCase3_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int BuildingCase3_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int BuildingCase3_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int BuildingCase3_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int BuildingCase3_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int BuildingCase3_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int BuildingCase3_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int BuildingCase3_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int BuildingCase3_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int BuildingCase3_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int BuildingCase3_checkForAsserts(DATA *data, threadData_t *threadData);
extern int BuildingCase3_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int BuildingCase3_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int BuildingCase3_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* BuildingCase3_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* BuildingCase3_relationDescription(int i);
extern void BuildingCase3_function_initSample(DATA *data, threadData_t *threadData);
extern int BuildingCase3_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BuildingCase3_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BuildingCase3_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BuildingCase3_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BuildingCase3_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BuildingCase3_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BuildingCase3_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BuildingCase3_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* BuildingCase3_linear_model_frame(void);
extern const char* BuildingCase3_linear_model_datarecovery_frame(void);
extern int BuildingCase3_mayer(DATA* data, modelica_real** res, short *);
extern int BuildingCase3_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int BuildingCase3_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int BuildingCase3_setInputData(DATA *data, const modelica_boolean file);
extern int BuildingCase3_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void BuildingCase3_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void BuildingCase3_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int BuildingCase3_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void BuildingCase3_read_simulation_info(SIMULATION_INFO* simulationData);
extern void BuildingCase3_read_input_fmu(MODEL_DATA* modelData);
extern void BuildingCase3_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int BuildingCase3_inputNames(DATA* data, char ** names);
extern int BuildingCase3_dataReconciliationInputNames(DATA* data, char ** names);
extern int BuildingCase3_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int BuildingCase3_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int BuildingCase3_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int BuildingCase3_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "BuildingCase3_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(BuildingCase3__MODEL_H) */


